name: Optimized Build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a release after successful build'
        required: false
        default: false
        type: boolean
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-optimized:
    name: Optimized Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: rbeaver-linux-x86_64
            archive: tar.gz
            
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: rbeaver-windows-x86_64.exe
            archive: zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb1-dev \
            libxrandr-dev \
            libxss-dev \
            libxcursor-dev \
            libxcomposite-dev \
            libasound2-dev \
            libxdamage-dev \
            libxfixes-dev \
            libxinerama-dev \
            libxi-dev \
            libxrender-dev \
            libxkbcommon-dev \
            libwayland-dev \
            libgl1-mesa-dev \
            libegl1-mesa-dev \
            upx-ucl

      - name: Install UPX (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win64.zip" -OutFile "upx.zip"
          Expand-Archive -Path "upx.zip" -DestinationPath "."
          Move-Item "upx-4.2.2-win64\upx.exe" "upx.exe"

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-optimized-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-optimized-cargo-

      - name: Build optimized release binary
        run: |
          cargo build --release --target ${{ matrix.target }}
        env:
          RUSTFLAGS: "-C target-cpu=native -C opt-level=3 -C lto=fat -C codegen-units=1 -C panic=abort"

      - name: Compress binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cp target/${{ matrix.target }}/release/rbeaver ${{ matrix.name }}
          strip ${{ matrix.name }}
          upx --best --lzma ${{ matrix.name }}

      - name: Compress binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          copy target\${{ matrix.target }}\release\rbeaver.exe ${{ matrix.name }}
          .\upx.exe --best --lzma ${{ matrix.name }}

      - name: Create archive (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czf ${{ matrix.name }}.tar.gz ${{ matrix.name }} README.md LICENSE

      - name: Create archive (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          7z a ${{ matrix.name }}.zip ${{ matrix.name }} README.md LICENSE

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-optimized
          path: |
            ${{ matrix.name }}.${{ matrix.archive }}
          retention-days: 90

  create-manual-release:
    name: Create Manual Release
    runs-on: ubuntu-latest
    needs: build-optimized
    if: ${{ github.event.inputs.create_release == 'true' }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -la artifacts/

      - name: Create manual release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: RBeaver ${{ github.event.inputs.release_tag }}
          files: |
            artifacts/rbeaver-linux-x86_64-optimized/rbeaver-linux-x86_64.tar.gz
            artifacts/rbeaver-windows-x86_64.exe-optimized/rbeaver-windows-x86_64.exe.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
